# version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kinemilk_backend
    ports:
      - "5000:5000"  # host:container
    volumes:
      - .:/home/kinemilk/backend
      - /home/kinemilk/backend/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      - redis
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: kinemilk_redis_service
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
